##服务端口号
server:
  port: 8100
eureka:
  instance:
    ##注册中心ip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      ##注册中心地址##注册中心地址 3 台 , 分割
      defaultZone:  http://${eureka.instance.hostname}:9100/eureka/
    ###因为自己是注册中心，是否需要将自己注册给注册中心（集群得时候需要为true）
    register-with-eureka: true
    ##因为自己是注册中心不需要去检索注册信息
    fetch-registry: true
###集群后就要定义服务名称 服务的别名---服务到注册中心的名称
spring:
  application:
    name: app-lhz-eureka